apiVersion: v1
kind: ReplicationController
metadata:
  name: mars-game-controller
  labels:
    app: mars-game-controller
spec:
  replicas: 1
  selector:
    name: controller
    version: "1"
  template:
    metadata:
      labels:
        name: controller
        version: "1"
    spec:
      containers:
        - name: controller
          image: emccode/mars-challenge-controller
          ports:
            - containerPort: 8080
              protocol: TCP
