apiVersion: v1
kind: ReplicationController
metadata:
  name: mars-game-gateway
  labels:
    app: mars-game-gateway
spec:
  replicas: 1
  selector:
    name: gateway
    version: "1"
  template:
    metadata:
      labels:
        name: gateway
        version: "1"
    spec:
      containers:
        - name: gateway
          image: tari/mars-game-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
