apiVersion: v1
kind: ReplicationController
metadata:
  name: mars-game-sensor
  labels:
    app: mars-game-sensor
spec:
  replicas: 1
  selector:
    name: sensor
    version: "1"
  template:
    metadata:
      labels:
        name: sensor
        version: "1"
    spec:
      containers:
        - name: sensor
          image: emccode/mars-challenge-client
          ports:
            - containerPort: 8080
              protocol: TCP
