kind: ReplicationController
apiVersion: v1
id: skydns
namespace: default
labels:
  k8s-app: skydns
spec:
  replicas: 1
  selector:
    k8s-app: skydns
  template:
    metadata:
      labels:
        k8s-app: skydns
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:latest
          command: [
            "/etcd",
            "-bind-addr=127.0.0.1",
            "-peer-bind-addr=127.0.0.1",
          ]
        - name: kube2sky
          image: kubernetes/kube2sky:1.0
          command: [
            # entrypoint = \"/kube2sky\",
            "-domain=kubernetes.local",
          ]
        - name: skydns
          image: kubernetes/skydns:latest
          command: [
            # entrypoint = \"/skydns\",
            "-machines=http://localhost:4001",
            "-addr=0.0.0.0:53",
            "-domain=kubernetes.local.",
          ]
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
